### ISSUE TITLE
Error after successful install

### ISSUE THREAD

**Issue by dimovskidamjan** [rubyonmac/rubyonmac-issues#15]
**In which version of Ruby on Mac did you find the bug?**
Basic

**Describe the bug**
I had several failed attempts to get the script to work, but I eventually succeeded. I tried the start over from scratch procedure and it seemed to work, however now when I try to install any gem I get an error:
```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /Users/<my_username>/.local/share/gem/specs
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:406:in `mkdir'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:406:in `fu_mkdir'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:384:in `block (2 levels) in mkdir_p'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:382:in `reverse_each'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:382:in `block in mkdir_p'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:374:in `each'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/fileutils.rb:374:in `mkdir_p'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/source.rb:151:in `fetch_spec'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/resolver/api_specification.rb:92:in `spec'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/resolver/installer_set.rb:98:in `add_always_install'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/dependency_installer.rb:322:in `resolve_dependencies'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:205:in `install_gem'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/command_manager.rb:191:in `process_args'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/command_manager.rb:149:in `run'
	/Users/<my_username>/.rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
	/Users/<my_username>/.rubies/ruby-3.2.1/bin/gem:10:in `<main>'
```

**Details about your Mac**
I already had homebrew installed.

**Please attach the Ruby on Mac log file**
[rom-basic.txt](https://github.com/rubyonmac/rubyonmac-issues/files/10873823/rom-basic.txt)

**Comment by monfresh** [comment]
It looks like your `/Users/<my_username>/.local/share/gem/specs` has the wrong permissions. Try fixing them:

```
sudo chown -R "$(whoami)" ~/.local
sudo chown -R "$(whoami)" ~/.local/share
sudo chown -R "$(whoami)" ~/.local/share/gem
```

The Prime and Ultimate versions of Ruby on Mac can automatically detect and fix these types of issues. If you ever want to upgrade, you can use the coupon code that's in the documentation.

Also, please don't attach the script itself. It has copyrighted code in it. It's the log file that you need to attach. It's called "rom-basic.log".

**Comment by dimovskidamjan** [comment]
@monfresh you are correct, however I was wondering if it's something that the script maybe did/should have done? And sorry for the log file (or in my case - the script itself) - that's my bad, I must have dragged in the wrong file.

**Comment by monfresh** [comment]
No problem about the log file. The Basic version of Ruby on Mac is very basic. It doesn't install any gems, so it doesn't check to see if there's something wrong that might affect gem installation. It's only guaranteed to work when you have a brand new and/or clean dev setup. It doesn't fix any issues automatically.

I stopped selling the Basic version at the end of November because of confusion around script failures or things failing after the script was done. Now, I get very little error reports from customers because Prime and Ultimate can automatically detect and fix common issues, and they also come with a reset mode that can start over from scratch in 1 minute, so people are happier.

**Comment by dimovskidamjan** [comment]
Understood. Thanks again, if I need it again I will consider upgrading 👋🏻

**Comment by monfresh** [comment]
You're welcome! 👋🏼
